In [1]:
import numpy as np

# Define the state transition function (transition probabilities)
transition_table = np.array([
    [0.8, 0.2, 0.0],  # Transition probabilities from "sunny" to ["sunny", "cloudy", "rainy"]
    [0.4, 0.4, 0.2],  # Transition probabilities from "cloudy" to ["sunny", "cloudy", "rainy"]
    [0.2, 0.6, 0.2]   # Transition probabilities from "rainy" to ["sunny", "cloudy", "rainy"]
])

# Define the initial state
initial_state = "cloudy"

# Function to simulate weather sequences
def simulate_weather_sequence(transition_matrix, initial_state, sequence_length):
    states = []
    current_state = initial_state

    for _ in range(sequence_length):
        states.append(current_state)
        # Use the transition matrix to determine the next state
        current_state = np.random.choice(["sunny", "cloudy", "rainy"], p=transition_matrix[current_state_to_index[current_state]])

    return states

# Dictionary to map state names to indices (0 for sunny, 1 for cloudy, 2 for rainy)
current_state_to_index = {"sunny": 0, "cloudy": 1, "rainy": 2}

# Simulate a weather sequence of length 10
weather_sequence = simulate_weather_sequence(transition_table, initial_state, sequence_length=1)

# Print the generated weather sequence
print(weather_sequence)

['cloudy']


This **stationary distribution** represents the long-term behavior of the chain, where the probabilities of being in different states stabilize over time, regardless of the initial state.<br>
Mathematically it is,
$$vA = v $$ such that
$ λ $ = 1

In [2]:
import numpy as np

# Define the state transition function (transition probabilities)
transition_table = np.array([
    [0.8, 0.2, 0.0],  # Transition probabilities from "sunny" to ["sunny", "cloudy", "rainy"]
    [0.4, 0.4, 0.2],  # Transition probabilities from "cloudy" to ["sunny", "cloudy", "rainy"]
    [0.2, 0.6, 0.2]   # Transition probabilities from "rainy" to ["sunny", "cloudy", "rainy"]
])

# Calculate the stationary distribution
eigenvalues, eigenvectors = np.linalg.eig(transition_table.T)
print(eigenvalues)
print(eigenvectors)
stationary_distribution = eigenvectors[:, np.where(np.isclose(eigenvalues, 1))[0][0]].real
print(stationary_distribution)
stationary_distribution /= stationary_distribution.sum()

# Display the stationary distribution
print("Stationary Distribution:")
print("Sunny: {:.4f}".format(stationary_distribution[0]))
print("Cloudy: {:.4f}".format(stationary_distribution[1]))
print("Rainy: {:.4f}".format(stationary_distribution[2]))


[ 1.          0.48284271 -0.08284271]
[[-0.90913729  0.81251992  0.23258782]
 [-0.40406102 -0.47596315 -0.79410449]
 [-0.10101525 -0.33655677  0.56151667]]
[-0.90913729 -0.40406102 -0.10101525]
Stationary Distribution:
Sunny: 0.6429
Cloudy: 0.2857
Rainy: 0.0714


In a Markov chain, a stationary distribution exists if and only if the chain is both *irreducible* and *aperiodic*. <br>
**Irreducibility**: A Markov chain is said to be irreducible if it is possible to reach any state from any other state, directly or indirectly, with positive probability. <br>
**Aperiodicity**: A Markov chain is said to be aperiodic if the greatest common divisor (GCD) of the lengths of all possible cycles in the chain is 1. In simpler terms, it means that the chain does not exhibit any regular or repeating patterns in its transitions

In [3]:
# Stationary distribution (from previous answer)
stationary_distribution = np.array([0.6429, 0.2857, 0.0714])

# Transition matrix (from the question)
transition_table = np.array([
    [0.8, 0.2, 0.0],  # Transition probabilities from "sunny" to ["sunny", "cloudy", "rainy"]
    [0.4, 0.4, 0.2],  # Transition probabilities from "cloudy" to ["sunny", "cloudy", "rainy"]
    [0.2, 0.6, 0.2]   # Transition probabilities from "rainy" to ["sunny", "cloudy", "rainy"]
])

# Calculate P(Yesterday | Today)
conditional_probabilities = transition_table * stationary_distribution.reshape(-1, 1)
print(conditional_probabilities)
conditional_probabilities /= conditional_probabilities.sum(axis=0)

# Display the conditional probability table
print("Conditional Probability Table (Yesterday | Today):")
print("               Yesterday")
print('----------------------------------- ')
print("Today     |  Sunny   Cloudy  Rainy")
print(f"Sunny     | {conditional_probabilities[0][0]:.4f}  {conditional_probabilities[1][0]:.4f}  {conditional_probabilities[2][0]:.4f}")
print(f"Cloudy    | {conditional_probabilities[0][1]:.4f}  {conditional_probabilities[1][1]:.4f}  {conditional_probabilities[2][1]:.4f}")
print(f"Rainy     | {conditional_probabilities[0][2]:.4f}  {conditional_probabilities[1][2]:.4f}  {conditional_probabilities[2][2]:.4f}")


[[0.51432 0.12858 0.     ]
 [0.11428 0.11428 0.05714]
 [0.01428 0.04284 0.01428]]
Conditional Probability Table (Yesterday | Today):
               Yesterday
----------------------------------- 
Today     |  Sunny   Cloudy  Rainy
Sunny     | 0.8000  0.1778  0.0222
Cloudy    | 0.4501  0.4000  0.1499
Rainy     | 0.0000  0.8001  0.1999


In [4]:
# Uniform prior probabilities
prior_distribution = np.array([1/3, 1/3, 1/3])

# Transition matrix (from the question)
transition_table = np.array([
    [0.8, 0.2, 0.0],  # Transition probabilities from "sunny" to ["sunny", "cloudy", "rainy"]
    [0.4, 0.4, 0.2],  # Transition probabilities from "cloudy" to ["sunny", "cloudy", "rainy"]
    [0.2, 0.6, 0.2]   # Transition probabilities from "rainy" to ["sunny", "cloudy", "rainy"]
])

# Calculate P(Yesterday | Today)
conditional_probabilities = transition_table * prior_distribution.reshape(-1, 1)
conditional_probabilities /= conditional_probabilities.sum(axis=0)

# Display the conditional probability table
print("Conditional Probability Table (Yesterday | Today):")
print("               Yesterday")
print('----------------------------------- ')
print("Today     |  Sunny   Cloudy  Rainy")

print(f"Sunny     | {conditional_probabilities[0][0]:.4f}  {conditional_probabilities[1][0]:.4f}  {conditional_probabilities[2][0]:.4f}")
print(f"Cloudy    | {conditional_probabilities[0][1]:.4f}  {conditional_probabilities[1][1]:.4f}  {conditional_probabilities[2][1]:.4f}")
print(f"Rainy     | {conditional_probabilities[0][2]:.4f}  {conditional_probabilities[1][2]:.4f}  {conditional_probabilities[2][2]:.4f}")

Conditional Probability Table (Yesterday | Today):
               Yesterday
----------------------------------- 
Today     |  Sunny   Cloudy  Rainy
Sunny     | 0.5714  0.2857  0.1429
Cloudy    | 0.1667  0.3333  0.5000
Rainy     | 0.0000  0.5000  0.5000


In [5]:
transition_table = np.array([
    [0.5, 0.5],
    [0.3, 0.7],
])
# Calculate the stationary distribution
eigenvalues, eigenvectors = np.linalg.eig(transition_table.T)
stationary_distribution = eigenvectors[:, np.where(np.isclose(eigenvalues, 1))[0][0]].real

# # Find index of eigenvalue 1
# stationary_index = np.argmin(np.abs(eigenvalues - 1))

# # Extract corresponding eigenvector
# stationary_distribution = np.real(eigenvectors[:, stationary_index])

stationary_distribution /= stationary_distribution.sum()
print(stationary_distribution)

[0.375 0.625]


In [25]:
A = transition_table
for _ in range(15):           # theoretically lim (n -> inf) A^n
    A = np.dot(transition_table,A)
print(A)

[[0.375 0.625]
 [0.375 0.625]]


In [8]:
state = {
    0:'Burger',
    1:'Pizza',
    2:'Hotdog'
}
state

{0: 'Burger', 1: 'Pizza', 2: 'Hotdog'}

$$A_{ij} = P(X_n = j | X_{n-1} = i)$$

In [13]:
# Transition matrix (from the question)
transition_matrix = np.array([
    [0.2, 0.6, 0.2],  # Transition probabilities from "Burger" to ["Burger", "Pizza", "Hotdog"]
    [0.3, 0.0, 0.7],  # Transition probabilities from "Pizza" to ["Burger", "Pizza", "Hotdog"]
    [0.5, 0.0, 0.5]   # Transition probabilities from "Hotdog" to ["Burger", "Pizza", "Hotdog"]
])

In [16]:
n = 15
start_state = 0
print(state[start_state],"--->",end = " ")
prev_state = start_state

while n-1:
  curr_state = np.random.choice([0,1,2],p = transition_matrix[prev_state])
  print(state[curr_state],"--->",end = " ")
  prev_state = curr_state
  n-=1
print("stop")

Burger ---> Hotdog ---> Hotdog ---> Burger ---> Pizza ---> Hotdog ---> Burger ---> Hotdog ---> Burger ---> Pizza ---> Hotdog ---> Hotdog ---> Hotdog ---> Hotdog ---> Burger ---> stop


## Approach 1: Monte Carlo

In [19]:
steps = 10**6
start_state = 0
pi = np.array([0,0,0])
pi[start_state] = 1
prev_state = start_state

i = 0
while i < steps:
  curr_state = np.random.choice([0,1,2],p = transition_matrix[prev_state])
  pi[curr_state] += 1
  prev_state = curr_state
  i += 1

print("pi = ",pi/steps)

pi =  [0.352102 0.211536 0.436363]


## Approach 2:  <br>
Repeated Matrix Multiplication
$$lim_{n \to ∞} A^n$$

In [29]:
steps = 10**6
A = transition_matrix
i = 0
while i < (steps):           # theoretically lim (n -> inf) A^n
    A = np.dot(transition_matrix,A)
    i += 1
print(A)
print(A[0])

[[0.35211268 0.21126761 0.43661972]
 [0.35211268 0.21126761 0.43661972]
 [0.35211268 0.21126761 0.43661972]]
[0.35211268 0.21126761 0.43661972]


## Approach 3: Finding the left Eigen Vectors

In [34]:
import scipy.linalg
values , left = scipy.linalg.eig(transition_matrix, right = False, left = True)

print("left eigen vectors\n", left)
print("eigen values", values)

left eigen vectors
 [[-0.58746336+0.j          0.16984156+0.35355339j  0.16984156-0.35355339j]
 [-0.35247801+0.j         -0.67936622+0.j         -0.67936622-0.j        ]
 [-0.72845456+0.j          0.50952467-0.35355339j  0.50952467+0.35355339j]]
eigen values [ 1.  +0.j        -0.15+0.3122499j -0.15-0.3122499j]


In [35]:
pi = left[:,0]
pi_normalised = [(x/np.sum(pi)).real for x in pi]
pi_normalised

[0.3521126760563379, 0.21126760563380304, 0.4366197183098591]

##P(Pizza --> Hotdog --> Hotdog --> Burger) <br>
=> P(X_0 = Pizza , X_1 = Hotdog, X_2 = Hotdog, X_3 = Burger) <br>
=> P(X_0 = Pizza).P(X_1 = Hotdog | X_0 = Pizza).P(X_2 = Hotdog | X_1 = Hotdog).P(X_3 = Burger | X_2 = Hotdog)

In [40]:
def find_prob(seq, A, pi):
  start_state = seq[0]
  prob = pi[start_state]
  prev_state = start_state
  for i in range(1, len(seq)):
    curr_state = seq[i]
    prob *= transition_matrix[prev_state][curr_state]
    prev_state = curr_state
  return prob
find_prob([1,2,2,0],transition_matrix,pi_normalised)

0.03697183098591553